- hosts: all
  become: yes
  vars_files:
    vars.yaml
  tasks:
    - name: modifying values
      template:
        src: httpd.conf
        dest: "{{ home }}"
      notify: restart service
  handlers:
    - name: restarting service
      service:
        name: httpd
        state: restarted
      listen: restart service


