- hosts: all
  name: installing jenkins software
  become: yes
  tasks:
    - name: updating packages
      yum:
        name: '*'
        state: present
    - name: adding url link
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: adding rpm key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
    - name: install java
      package:
        name: java-11*
        state: present
    - name: installing jenkins
      yum:
        name: jenkins
        state: latest
    - name: starting jenkins
      systemd:
        enabled: yes
        name: jenkins
        state: started
